# Generated by Django 5.0.7 on 2024-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('script', models.CharField(max_length=100)),
                ('horario_execucao', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Agendado', max_length=50)),
            ],
        ),
    ]
