# Generated by Django 5.0.7 on 2024-08-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automacao',
            name='frequencia',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Semanal', 'Semanal')], default='00:00:00', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automacao',
            name='horario_execucao',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='script',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='status',
            field=models.CharField(default='Agendado', max_length=20),
        ),
    ]
