# Generated by Django 5.0.7 on 2024-08-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orquestrador', '0002_automacao_frequencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automacao',
            name='frequencia',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Única Vez', 'Única Vez')], max_length=50),
        ),
    ]
